apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmware-exporter
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: vmware-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 30s
