apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmware-exporter
  template:
    metadata:
      labels:
        app: vmware-exporter
    spec:
      containers:
        - name: vmware-exporter
          image: pryorda/vmware_exporter:latest
          ports:
            - containerPort: 9272
          env:
            - name: VSPHERE_HOST
              value: "10.10.86.251"   # IP vCenter
            - name: VSPHERE_USER
              valueFrom:
                secretKeyRef:
                  name: vmware-exporter-secret
                  key: VSPHERE_USER
            - name: VSPHERE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vmware-exporter-secret
                  key: VSPHERE_PASSWORD
            - name: VSPHERE_IGNORE_SSL
              value: "true"
